version: '3.7'

services:
  frontend:
    build: .
    env_file:
      - .env
    stdin_open: true
    tty: true
    restart: unless-stopped
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    command: npm start
